# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request event but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      - name: Bash
        run: |
          firstline=$(sed '1q;d' README.md);
          secondline=$(sed '2q;d' README.md);
          firstLineChar=${firstline:0:1};
          secondLineChar=${secondline:0:1};
          echo $firstLineChar;
          echo $secondLineChar;
          if [ "$firstLineChar" == "#" ]; then echo '::set-output name=titleResult::True' ; else echo '::set-output name=titleResult::False' ; fi;
          if [ -n "$secondLineChar" ]; then echo '::set-output name=desResult::True'; else echo '::set-output name=desResult::False'; fi;
          echo
          arr=();
          while IFS= read -r line; do arr+=(${#line}) ; done < README.md;
          echo ${arr[0]};
          if [[ "${arr[0]}" -le 70 && "${arr[0]}" -ge 50 ]]; then echo '::set-output name=titleLenGood::True'; else echo '::set-output name=titleLenGood::False'; fi;
          unset arr[0];
          total=0;
          for i in ${arr[@]}; do
          let total+=$i;
          done;
          if [[ ${total} -le 170 && ${total} -ge 140 ]]; then echo '::set-output name=descLenGood::True'; else echo '::set-output name=desLenGood::False'; fi;
        id: script

      - name: Check if for heading length
        run: |
          if [[ ${{ steps.script.outputs.titleResult }} == True && ${{ steps.script.outputs.titleLenGood }} == False ]] ;
          then exit 1; fi ;

      - name: Check if for description length
        run: |
          if [ ${{ steps.script.outputs.desResult }} == True && ${{ steps.script.outputs.descLenGood }} == False ];
          then exit 1; fi ;
